name: Markdown

on:
  pull_request:
    paths:
      - '*.md'
  push:
    paths:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint changelog file
        uses: docker://avtodev/markdown-lint:v1 # fastest way
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './*.md'
