name: Markdown

on:
  pull_request:
    paths:
      - '*.md'
  push:
    paths:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - run: markdownlint **/*.md --ignore node_modules